services:
  brewintelligence-app:
    image: joshdavidang/backend-brewintelligence-app:latest
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    volumes:
      - /tmp
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env.dev
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
