name: Format and build frontend

on:
    workflow_call:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

jobs:
  run_formatter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Check out the code.
        uses: actions/checkout@v4.2.1
      - name: Set up NodeJS (for compatibility)
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 22.x
      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash
      - name: Set up Bun path
        run: echo "$HOME/.bun/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: bun install
      - name: Build the frontend
        run: bun run build
