name: Format and build backend

on:
  workflow_call:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: backend
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Install dependencies
      run: mvn clean install -U
    - name: Build with Maven
      run: mvn -B package
    - name: Copy JAR to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: /target/brewintelligence-backend-0.0.1-SNAPSHOT.jar
          target: /home/ec2-user/myapp/myapp.jar
    - name: Restart app on EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            /home/ec2-user/restart-app.sh
